# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech64_10.4/win64
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z045fbg676-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/jiaweiwei/Vivado workspace/tools/complex_abs_power2_35_1dsp/complex_abs_power2_35_1dsp.cache/wt} [current_project]
set_property parent.project_path {E:/jiaweiwei/Vivado workspace/tools/complex_abs_power2_35_1dsp/complex_abs_power2_35_1dsp.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{e:/jiaweiwei/Vivado workspace/tools/complex_abs_power2_35_1dsp/complex_abs_power2_35_1dsp.srcs/sources_1}} [current_project]
add_files -quiet {{E:/jiaweiwei/Vivado workspace/tools/complex_abs_power2_35_1dsp/complex_abs_power2_35_1dsp.runs/dsp48_mul_add_ip_synth_1/dsp48_mul_add_ip.dcp}}
set_property used_in_implementation false [get_files {{E:/jiaweiwei/Vivado workspace/tools/complex_abs_power2_35_1dsp/complex_abs_power2_35_1dsp.runs/dsp48_mul_add_ip_synth_1/dsp48_mul_add_ip.dcp}}]
read_verilog -library xil_defaultlib {{E:/jiaweiwei/Vivado workspace/tools/complex_abs_power2_35_1dsp/complex_abs_power2_35_1dsp.srcs/sources_1/code/complex_abs_power2_35_1dsp.v}}
synth_design -top complex_abs_power2_35_1dsp -part xc7z045fbg676-3
write_checkpoint -noxdef complex_abs_power2_35_1dsp.dcp
catch { report_utilization -file complex_abs_power2_35_1dsp_utilization_synth.rpt -pb complex_abs_power2_35_1dsp_utilization_synth.pb }
