######################################################################
##
## Filename: complex_multiplier_18_17.udo
## Created on: Thu Nov 12 23:56:30 中国标准时间 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
