# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dsp48_mul_ip/dsp48_mul_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp48_mul_ip || ORIG_REF_NAME==dsp48_mul_ip}]
